"""The Chameleon - Interactive Dice Game CLI.

A Python CLI version of The Chameleon game with dice rolling and topic grids.
"""

from collections import defaultdict
from dataclasses import dataclass, field
import random
import sys

import typer

# Color/style constants
BOLD_BLUE_STYLE = "bold blue"

try:
    from rich import box
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table
    from rich.text import Text

except ImportError:
    sys.stderr.write("Error: rich library is required. Install it with: pip install rich\n")
    sys.exit(1)


# Game data - topics and their items
GAME_DATA: dict[str, list[str]] = {
    "Games": [
        "Monopoly",
        "Scrabble",
        "Risk",
        "Chess",
        "Checkers",
        "Uno",
        "Clue",
        "Battleship",
        "Operation",
        "Twister",
        "Pictionary",
        "Jenga",
        "Trivial Pursuit",
        "Codenames",
        "Connect 4",
        "Guess Who",
    ],
    "Video Games": [
        "Super Mario",
        "Minecraft",
        "Grand Theft Auto",
        "Call of Duty",
        "Pokémon",
        "The Sims",
        "FIFA",
        "Tetris",
        "League of Legends",
        "Zelda",
        "Skyrim",
        "Fortnite",
        "Assassin's Creed",
        "Dark Souls",
        "God of War",
        "World of Warcraft",
    ],
    "Food": [
        "Pizza",
        "Pasta",
        "Bread",
        "Rice",
        "Potatoes",
        "Fish",
        "Chicken",
        "Beef",
        "Soup",
        "Salad",
        "Eggs",
        "Cheese",
        "Sausage",
        "Chocolate",
        "Ice Cream",
        "Cake",
    ],
    "Fast Food & Snacks": [
        "Burger",
        "Hot Dog",
        "Fries",
        "Donut",
        "Nachos",
        "Popcorn",
        "Pretzel",
        "Sandwich",
        "Taco",
        "Burrito",
        "Kebab",
        "Pizza Slice",
        "Chicken Nuggets",
        "Spring Rolls",
        "Onion Rings",
        "Wrap",
    ],
    "Ice Cream Flavors": [
        "Vanilla",
        "Chocolate",
        "Strawberry",
        "Pistachio",
        "Hazelnut",
        "Mint",
        "Lemon",
        "Coffee",
        "Caramel",
        "Coconut",
        "Banana",
        "Berries",
        "Stracciatella",
        "Zabaglione",
        "Tiramisu",
        "White Chocolate",
    ],
    "Transport": [
        "Car",
        "Bus",
        "Train",
        "Airplane",
        "Helicopter",
        "Boat",
        "Ship",
        "Motorcycle",
        "Bicycle",
        "Submarine",
        "Tram",
        "Tank",
        "Spaceship",
        "Hot Air Balloon",
        "Cable Car",
        "Hovercraft",
    ],
    "Rooms": [
        "Kitchen",
        "Bedroom",
        "Bathroom",
        "Living Room",
        "Dining Room",
        "Office",
        "Hallway",
        "Attic",
        "Basement",
        "Garage",
        "Pantry",
        "Nursery",
        "Balcony",
        "Terrace",
        "Closet",
        "Cellar",
    ],
    "Phobias": [
        "Spiders",
        "Snakes",
        "Heights",
        "Darkness",
        "Clowns",
        "Germs",
        "Needles",
        "Flying",
        "Dogs",
        "Birds",
        "Insects",
        "Rats",
        "Ghosts",
        "Monsters",
        "Roller Coasters",
        "Enclosed Spaces",
    ],
    "Musical Instruments": [
        "Guitar",
        "Piano",
        "Violin",
        "Drums",
        "Flute",
        "Saxophone",
        "Trumpet",
        "Cello",
        "Harp",
        "Clarinet",
        "Harmonica",
        "Ukulele",
        "Accordion",
        "Banjo",
        "Bagpipes",
        "Xylophone",
    ],
    "Sports": [
        "Football (Soccer)",
        "Basketball",
        "Tennis",
        "Cricket",
        "Rugby",
        "Golf",
        "Swimming",
        "Volleyball",
        "Cycling",
        "Ice Hockey",
        "American Football",
        "Baseball",
        "Table Tennis",
        "Badminton",
        "Athletics",
        "Gymnastics",
    ],
    "Countries": [
        "United States",
        "Canada",
        "Mexico",
        "Brazil",
        "Argentina",
        "United Kingdom",
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Netherlands",
        "Poland",
        "Sweden",
        "Norway",
        "China",
        "Japan",
        "India",
        "South Korea",
        "Australia",
        "Egypt",
        "South Africa",
        "Nigeria",
        "Kenya",
        "Morocco",
        "Thailand",
    ],
    "Cities": [
        "New York City",
        "Los Angeles",
        "Chicago",
        "London",
        "Paris",
        "Rome",
        "Berlin",
        "Madrid",
        "Vienna",
        "Amsterdam",
        "Tokyo",
        "Beijing",
        "Seoul",
        "Mumbai",
        "Bangkok",
        "Sydney",
        "Rio de Janeiro",
        "Cape Town",
    ],
    "Geography": [
        "Mountain",
        "River",
        "Lake",
        "Sea",
        "Ocean",
        "Island",
        "Desert",
        "Forest",
        "Jungle",
        "Valley",
        "Glacier",
        "Waterfall",
        "Volcano",
        "Cave",
        "Swamp",
        "Tundra",
    ],
    "Biomes": [
        "Tropical Rainforest",
        "Savanna",
        "Desert",
        "Temperate Forest",
        "Taiga",
        "Tundra",
        "Grassland",
        "Mediterranean Scrub",
        "Mangrove Forest",
        "Swamp",
        "Coral Reef",
        "Temperate Rainforest",
        "Alpine",
        "Steppe",
        "Wetlands",
        "Boreal Forest",
    ],
    "Plants": [
        "Oak",
        "Beech",
        "Pine",
        "Palm",
        "Baobab",
        "Bamboo",
        "Sunflower",
        "Daisy",
        "Rose",
        "Tulip",
        "Cactus",
        "Eucalyptus",
        "Maple",
        "Olive Tree",
        "Rice",
        "Wheat",
    ],
    "World Landmarks": [
        "Eiffel Tower",
        "Statue of Liberty",
        "Great Wall of China",
        "Colosseum",
        "Machu Picchu",
        "Taj Mahal",
        "Pyramids of Giza",
        "Christ the Redeemer",
        "Big Ben",
        "Stonehenge",
        "Acropolis of Athens",
        "Leaning Tower of Pisa",
        "Sydney Opera House",
        "Hagia Sophia",
        "Grand Canyon",
        "Mount Everest",
    ],
    "Civilizations": [
        "Romans",
        "Egyptians",
        "Greeks",
        "Persians",
        "Maya",
        "Aztecs",
        "Inca",
        "Chinese",
        "Japanese",
        "Vikings",
        "Mongols",
        "Celts",
        "Spartans",
        "Ottomans",
        "Etruscans",
        "Gauls",
    ],
    "Regions & States": [
        "Bavaria",
        "Berlin",
        "Hesse",
        "North Rhine-Westphalia",
        "Saxony",
        "Vienna",
        "Tyrol",
        "Lombardy",
        "Tuscany",
        "Lazio",
        "Sicily",
        "Sardinia",
        "Piedmont",
        "Emilia-Romagna",
        "Salzburg",
        "Styria",
    ],
    "Movies": [
        "The Godfather",
        "Titanic",
        "Jurassic Park",
        "Jaws",
        "Avatar",
        "The Matrix",
        "Inception",
        "Gladiator",
        "Pulp Fiction",
        "Fight Club",
        "The Shawshank Redemption",
        "Forrest Gump",
        "Back to the Future",
        "Star Wars",
        "The Dark Knight",
        "The Lord of the Rings",
    ],
    "TV Series": [
        "Friends",
        "Breaking Bad",
        "Game of Thrones",
        "The Simpsons",
        "The Big Bang Theory",
        "Stranger Things",
        "Star Trek",
        "The Walking Dead",
        "The X-Files",
        "How I Met Your Mother",
        "Lost",
        "Black Mirror",
        "Sherlock",
        "Grey's Anatomy",
        "Rick and Morty",
        "The Office",
    ],
    "Film Genres": [
        "Action",
        "Comedy",
        "Drama",
        "Horror",
        "Thriller",
        "Science Fiction",
        "Fantasy",
        "Romantic Comedy",
        "Animation",
        "Documentary",
        "Crime",
        "Gangster",
        "Western",
        "War",
        "Musical",
        "Christmas",
    ],
    "Sci-Fi & Fantasy": [
        "Star Wars",
        "The Lord of the Rings",
        "Dune",
        "Blade Runner",
        "The Matrix",
        "2001: A Space Odyssey",
        "Alien",
        "Terminator",
        "Doctor Who",
        "The War of the Worlds",
        "The NeverEnding Story",
        "Edward Scissorhands",
        "WALL-E",
        "Back to the Future",
        "Jurassic Park",
        "Game of Thrones",
    ],
    "Animated Films": [
        "Toy Story",
        "The Lion King",
        "Shrek",
        "Finding Nemo",
        "Frozen",
        "Inside Out",
        "Spirited Away",
        "Kung Fu Panda",
        "Ratatouille",
        "Up",
        "Monsters, Inc.",
        "Zootopia",
        "Cars",
        "Wall-E",
        "Ice Age",
        "The Incredibles",
    ],
    "Animated Series": [
        "The Simpsons",
        "Rick and Morty",
        "Tom and Jerry",
        "SpongeBob SquarePants",
        "Avatar: The Last Airbender",
        "Naruto",
        "Dragon Ball",
        "One Piece",
        "Pokémon",
        "Family Guy",
        "Adventure Time",
        "Scooby-Doo",
        "Ben 10",
        "Gravity Falls",
        "Teenage Mutant Ninja Turtles",
        "Phineas and Ferb",
    ],
    "Musicals": [
        "The Phantom of the Opera",
        "Les Misérables",
        "The Lion King",
        "Cats",
        "Hamilton",
        "Chicago",
        "Mamma Mia!",
        "Wicked",
        "West Side Story",
        "Oliver!",
        "Annie",
        "Hairspray",
        "Jersey Boys",
        "School of Rock",
        "The Book of Mormon",
        "42nd Street",
    ],
    "Children's Books": [
        "The Hobbit",
        "Peter Pan",
        "Harry Potter and the Philosopher's Stone",
        "Alice in Wonderland",
        "Charlie and the Chocolate Factory",
        "The Lion, the Witch and the Wardrobe",
        "Winnie-the-Pooh",
        "The Jungle Book",
        "Pinocchio",
        "101 Dalmatians",
        "The Wizard of Oz",
        "The Little Prince",
        "Treasure Island",
        "Dumbo",
        "A Christmas Carol",
        "Where the Wild Things Are",
    ],
    "Literary Classics": [
        "The Lord of the Rings",
        "1984",
        "Crime and Punishment",
        "War and Peace",
        "The Divine Comedy",
        "The Odyssey",
        "Don Quixote",
        "Anna Karenina",
        "Wuthering Heights",
        "Moby Dick",
        "The Picture of Dorian Gray",
        "The Iliad",
        "One Hundred Years of Solitude",
        "The Decameron",
        "The Diary of Anne Frank",
        "Doctor Zhivago",
    ],
    "Authors": [
        "William Shakespeare",
        "Jane Austen",
        "Charles Dickens",
        "Leo Tolstoy",
        "Fyodor Dostoevsky",
        "Victor Hugo",
        "Oscar Wilde",
        "Mark Twain",
        "Agatha Christie",
        "Stephen King",
        "J. K. Rowling",
        "J. R. R. Tolkien",
        "George Orwell",
        "Ernest Hemingway",
        "Edgar Allan Poe",
        "Gabriel García Márquez",
    ],
    "Fantasy & Adventure Books": [
        "Harry Potter",
        "The Chronicles of Narnia",
        "The NeverEnding Story",
        "Percy Jackson and the Olympians",
        "His Dark Materials",
        "The Hobbit",
        "The Lord of the Rings",
        "Alice in Wonderland",
        "Gulliver's Travels",
        "Treasure Island",
        "The Jungle Book",
        "The Princess Bride",
        "The War of the Worlds",
        "Dune",
        "The Martian",
        "The Hitchhiker's Guide to the Galaxy",
    ],
    "Philosophers": [
        "Socrates",
        "Plato",
        "Aristotle",
        "Confucius",
        "Avicenna",
        "René Descartes",
        "Immanuel Kant",
        "Friedrich Nietzsche",
        "Jean-Paul Sartre",
        "John Locke",
        "David Hume",
        "Jean-Jacques Rousseau",
        "Georg Wilhelm Friedrich Hegel",
        "Ludwig Wittgenstein",
        "Simone de Beauvoir",
        "Hannah Arendt",
    ],
    "Poets": [
        "Homer",
        "Dante Alighieri",
        "William Blake",
        "Johann Wolfgang von Goethe",
        "Emily Dickinson",
        "Walt Whitman",
        "Rumi",
        "Hafez",
        "Saadi",
        "Ferdowsi",
        "Pablo Neruda",
        "Federico García Lorca",
        "T. S. Eliot",
        "Sylvia Plath",
        "Langston Hughes",
        "Robert Frost",
    ],
    "Historical Figures": [
        "Jesus Christ",
        "Napoleon Bonaparte",
        "Julius Caesar",
        "Cleopatra",
        "Charlemagne",
        "Christopher Columbus",
        "Leonardo da Vinci",
        "Galileo Galilei",
        "Isaac Newton",
        "Charles Darwin",
        "Albert Einstein",
        "Wolfgang Amadeus Mozart",
        "Joan of Arc",
        "Winston Churchill",
        "Mahatma Gandhi",
        "Martin Luther King Jr.",
    ],
    "World Leaders & Politicians": [
        "George Washington",
        "Abraham Lincoln",
        "Theodore Roosevelt",
        "Franklin D. Roosevelt",
        "John F. Kennedy",
        "Nelson Mandela",
        "Angela Merkel",
        "Barack Obama",
        "Donald Trump",
        "Joe Biden",
        "Vladimir Putin",
        "Margaret Thatcher",
        "Indira Gandhi",
        "Golda Meir",
        "Pope Francis",
        "Napoleon Bonaparte",
    ],
    "Scientists & Inventors": [
        "Albert Einstein",
        "Isaac Newton",
        "Nikola Tesla",
        "Thomas Edison",
        "Alexander Graham Bell",
        "Marie Curie",
        "Galileo Galilei",
        "Charles Darwin",
        "Louis Pasteur",
        "Michael Faraday",
        "James Watt",
        "Johannes Gutenberg",
        "Alan Turing",
        "Stephen Hawking",
        "Leonardo da Vinci",
        "Guglielmo Marconi",
    ],
    "Artists & Cultural Icons": [
        "Leonardo da Vinci",
        "Michelangelo",
        "Vincent van Gogh",
        "Pablo Picasso",
        "Claude Monet",
        "Rembrandt",
        "Salvador Dalí",
        "Andy Warhol",
        "Banksy",
        "Frida Kahlo",
        "Jackson Pollock",
        "Marc Chagall",
        "Henri Matisse",
        "Giotto",
        "Caravaggio",
        "Katsushika Hokusai",
    ],
    "Entertainment Icons": [
        "Charlie Chaplin",
        "Marilyn Monroe",
        "Elvis Presley",
        "Michael Jackson",
        "Freddie Mercury",
        "Madonna",
        "The Beatles",
        "Walt Disney",
        "Steven Spielberg",
        "Alfred Hitchcock",
        "Bruce Lee",
        "Arnold Schwarzenegger",
        "Tom Hanks",
        "Meryl Streep",
        "Johnny Depp",
        "Leonardo DiCaprio",
    ],
    "Zoo Animals": [
        "Elephant",
        "Giraffe",
        "Lion",
        "Tiger",
        "Leopard",
        "Zebra",
        "Rhinoceros",
        "Hippopotamus",
        "Gorilla",
        "Chimpanzee",
        "Meerkat",
        "Ostrich",
        "Alligator",
        "Wolf",
        "Bear",
        "Lynx",
    ],
    "Jungle Animals": [
        "Monkey",
        "Chimpanzee",
        "Sloth",
        "Toucan",
        "Anaconda",
        "Tiger",
        "Jaguar",
        "Tapir",
        "Boar",
        "Frog",
        "Crocodile",
        "Anteater",
        "Okapi",
        "Lemur",
        "Parrot",
        "Poison Dart Frog",
    ],
    "Under the Sea": [
        "Octopus",
        "Shark",
        "Dolphin",
        "Whale",
        "Killer Whale",
        "Sea Turtle",
        "Clownfish",
        "Seahorse",
        "Jellyfish",
        "Starfish",
        "Lobster",
        "Crab",
        "Manta Ray",
        "Anglerfish",
        "Narwhal",
        "Giant Squid",
    ],
    "Pets": [
        "Dog",
        "Cat",
        "Rabbit",
        "Hamster",
        "Guinea Pig",
        "Parrot",
        "Goldfish",
        "Turtle",
        "Snake",
        "Iguana",
        "Ferret",
        "Hedgehog",
        "Chinchilla",
        "Mouse",
        "Lizard",
        "Tarantula",
    ],
    "Insects": [
        "Ant",
        "Bee",
        "Butterfly",
        "Dragonfly",
        "Ladybug",
        "Beetle",
        "Grasshopper",
        "Cricket",
        "Mosquito",
        "Fly",
        "Wasp",
        "Moth",
        "Termite",
        "Cockroach",
        "Flea",
        "Stick Insect",
    ],
    "Birds": [
        "Eagle",
        "Owl",
        "Hawk",
        "Falcon",
        "Vulture",
        "Parrot",
        "Crow",
        "Pigeon",
        "Sparrow",
        "Flamingo",
        "Pelican",
        "Albatross",
        "Hummingbird",
        "Woodpecker",
        "Stork",
        "Kingfisher",
    ],
    "Plains Animals": [
        "Elephant",
        "Buffalo",
        "Cheetah",
        "Gazelle",
        "Giraffe",
        "Lion",
        "Hyena",
        "Rhinoceros",
        "Zebra",
        "Wildebeest",
        "Meerkat",
        "Ostrich",
        "Leopard",
        "Warthog",
        "Antelope",
        "Python",
    ],
    "Mythical Creatures": [
        "Dragon",
        "Unicorn",
        "Phoenix",
        "Griffin",
        "Pegasus",
        "Cyclops",
        "Minotaur",
        "Hydra",
        "Sphinx",
        "Centaur",
        "Mermaid",
        "Werewolf",
        "Vampire",
        "Troll",
        "Yeti",
        "Loch Ness Monster",
    ],
    "Fantasy Races": [
        "Elves",
        "Dwarves",
        "Humans",
        "Orcs",
        "Goblins",
        "Giants",
        "Trolls",
        "Ents",
        "Fairies",
        "Sprites",
        "Vampires",
        "Werewolves",
        "Dragons",
        "Centaurs",
        "Undead",
        "Shapeshifters",
    ],
    "Superheroes": [
        "Batman",
        "Superman",
        "Spider-Man",
        "Iron Man",
        "Captain America",
        "Thor",
        "Hulk",
        "Wonder Woman",
        "Black Widow",
        "Black Panther",
        "Doctor Strange",
        "Flash",
        "Aquaman",
        "Wolverine",
        "Deadpool",
        "Captain Marvel",
    ],
    "Fictional Characters": [
        "James Bond",
        "Indiana Jones",
        "Harry Potter",
        "Frodo Baggins",
        "Sherlock Holmes",
        "Katniss Everdeen",
        "Lara Croft",
        "Princess Leia",
        "Darth Vader",
        "Luke Skywalker",
        "Wonder Woman",
        "Homer Simpson",
        "Mario",
        "Gandalf",
        "Dracula",
        "Robin Hood",
    ],
    "Harry Potter Characters": [
        "Harry Potter",
        "Hermione Granger",
        "Ron Weasley",
        "Albus Dumbledore",
        "Severus Snape",
        "Lord Voldemort",
        "Minerva McGonagall",
        "Rubeus Hagrid",
        "Draco Malfoy",
        "Luna Lovegood",
        "Ginny Weasley",
        "Neville Longbottom",
        "Sirius Black",
        "Remus Lupin",
        "Bellatrix Lestrange",
        "Lucius Malfoy",
    ],
    "Super Mario Characters": [
        "Mario",
        "Luigi",
        "Princess Peach",
        "Bowser",
        "Yoshi",
        "Toad",
        "Daisy",
        "Wario",
        "Waluigi",
        "Bowser Jr.",
        "Donkey Kong",
        "Goomba",
        "Koopa Troopa",
        "Boo",
        "Chain Chomp",
        "Piranha Plant",
    ],
    "Music Genres": [
        "Rock",
        "Pop",
        "Classical",
        "Hip Hop",
        "Rap",
        "Jazz",
        "Blues",
        "Heavy Metal",
        "Electronic",
        "Techno",
        "House",
        "Disco",
        "Reggae",
        "Country",
        "Punk",
        "Indie",
    ],
    "Bands": [
        "The Beatles",
        "The Rolling Stones",
        "Queen",
        "Pink Floyd",
        "Led Zeppelin",
        "Nirvana",
        "AC/DC",
        "Metallica",
        "U2",
        "Coldplay",
        "Radiohead",
        "Red Hot Chili Peppers",
        "Linkin Park",
        "Green Day",
        "Guns N' Roses",
        "ABBA",
    ],
    "Music Artists": [
        "Michael Jackson",
        "Elvis Presley",
        "Madonna",
        "Freddie Mercury",
        "Beyoncé",
        "Taylor Swift",
        "Eminem",
        "Rihanna",
        "Ed Sheeran",
        "Drake",
        "Adele",
        "Justin Bieber",
        "Kanye West",
        "Bruno Mars",
        "Lady Gaga",
        "The Weeknd",
    ],
    "Singers": [
        "Frank Sinatra",
        "Whitney Houston",
        "Aretha Franklin",
        "Bob Dylan",
        "Prince",
        "David Bowie",
        "Stevie Wonder",
        "Celine Dion",
        "Ariana Grande",
        "Billie Eilish",
        "Shakira",
        "Robbie Williams",
        "Katy Perry",
        "Pink",
        "Avril Lavigne",
        "Bruno Mars",
    ],
    "Classical Composers": [
        "Wolfgang Amadeus Mozart",
        "Ludwig van Beethoven",
        "Johann Sebastian Bach",
        "Franz Schubert",
        "Joseph Haydn",
        "Antonio Vivaldi",
        "Pyotr Ilyich Tchaikovsky",
        "Frédéric Chopin",
        "Claude Debussy",
        "Richard Wagner",
        "Giuseppe Verdi",
        "Johannes Brahms",
        "George Frideric Handel",
        "Gustav Mahler",
        "Sergei Rachmaninoff",
        "Igor Stravinsky",
    ],
    "Musical Instruments (Music)": [
        "Guitar",
        "Piano",
        "Violin",
        "Drums",
        "Bass Guitar",
        "Saxophone",
        "Trumpet",
        "Flute",
        "Cello",
        "Clarinet",
        "Harp",
        "Accordion",
        "Trombone",
        "Oboe",
        "Tuba",
        "Ukulele",
    ],
    "Jobs & Professions": [
        "Doctor",
        "Nurse",
        "Teacher",
        "Professor",
        "Engineer",
        "Programmer",
        "Accountant",
        "Lawyer",
        "Police Officer",
        "Security Guard",
        "Chef",
        "Architect",
        "Carpenter",
        "Electrician",
        "Mechanic",
        "Farmer",
    ],
    "School Subjects": [
        "Mathematics",
        "English",
        "History",
        "Geography",
        "Biology",
        "Chemistry",
        "Physics",
        "Art",
        "Music",
        "Physical Education",
        "Philosophy",
        "Economics",
        "Literature",
        "Religion",
        "Latin",
        "Technology",
    ],
    "Fields of Study": [
        "Computer Science",
        "Electrical Engineering",
        "Mechanical Engineering",
        "Civil Engineering",
        "Business Administration",
        "Medicine",
        "Law",
        "Psychology",
        "Sociology",
        "Biology",
        "Physics",
        "Mathematics",
        "Architecture",
        "Economics",
        "Education",
        "Linguistics",
    ],
    "University Faculties": [
        "Engineering",
        "Medicine",
        "Law",
        "Economics",
        "Computer Science",
        "Mathematics",
        "Physics",
        "Biology",
        "Psychology",
        "Political Science",
        "Architecture",
        "Literature",
        "Languages",
        "History",
        "Philosophy",
        "Nursing",
    ],
    "Mathematics": [
        "Addition",
        "Subtraction",
        "Multiplication",
        "Division",
        "Algebra",
        "Geometry",
        "Trigonometry",
        "Calculus",
        "Derivative",
        "Integral",
        "Limit",
        "Function",
        "Equation",
        "Logarithm",
        "Factorial",
        "Probability",
    ],
    "Geometry": [
        "Point",
        "Line",
        "Plane",
        "Angle",
        "Triangle",
        "Square",
        "Rectangle",
        "Circle",
        "Radius",
        "Diameter",
        "Parallel",
        "Perpendicular",
        "Symmetry",
        "Polygon",
        "Area",
        "Volume",
    ],
    "Brands & Companies": [
        "Apple",
        "Google",
        "Microsoft",
        "Amazon",
        "Samsung",
        "Tesla",
        "BMW",
        "Mercedes-Benz",
        "Toyota",
        "Nike",
        "Adidas",
        "Coca-Cola",
        "Nestlé",
        "McDonald's",
        "Disney",
        "Netflix",
    ],
    "Technology Companies": [
        "Apple",
        "Microsoft",
        "Google",
        "Amazon",
        "Meta",
        "Samsung",
        "Intel",
        "AMD",
        "NVIDIA",
        "IBM",
        "Oracle",
        "Huawei",
        "Sony",
        "LG",
        "Dell",
        "HP",
    ],
    "Software & Programs": [
        "Microsoft Word",
        "Microsoft Excel",
        "PowerPoint",
        "Adobe Photoshop",
        "Adobe Illustrator",
        "Google Chrome",
        "Mozilla Firefox",
        "Zoom",
        "Skype",
        "Telegram",
        "WhatsApp",
        "Steam",
        "TeamViewer",
        "CCleaner",
        "VLC Media Player",
        "OpenOffice",
    ],
    "Social Media & Platforms": [
        "Facebook",
        "Instagram",
        "Twitter",
        "TikTok",
        "YouTube",
        "WhatsApp",
        "Telegram",
        "Snapchat",
        "Reddit",
        "Discord",
        "LinkedIn",
        "Pinterest",
        "Tumblr",
        "Wikipedia",
        "Twitch",
        "OnlyFans",
    ],
    "Electronic Devices": [
        "Smartphone",
        "Laptop",
        "Desktop Computer",
        "Tablet",
        "Smartwatch",
        "Television",
        "Radio",
        "Speaker",
        "Printer",
        "Router",
        "Camera",
        "Projector",
        "Game Console",
        "VR Headset",
        "Drone",
        "Smart Speaker",
    ],
    "Mechanical Devices": [
        "Steam Engine",
        "Clockwork",
        "Gear",
        "Pulley",
        "Lever",
        "Crankshaft",
        "Brake",
        "Clutch",
        "Watermill",
        "Typewriter",
        "Gramophone",
        "Lock",
        "Jack",
        "Scale",
        "Screwdriver",
        "Piston",
    ],
    "Hobbies & Leisure": [
        "Reading",
        "Cooking",
        "Baking",
        "Gardening",
        "Painting",
        "Drawing",
        "Photography",
        "Traveling",
        "Hiking",
        "Walking",
        "Cycling",
        "Swimming",
        "Yoga",
        "DIY",
        "Model Making",
        "Board Games",
    ],
    "Indoor Hobbies": [
        "Reading",
        "Cooking",
        "Baking",
        "Knitting",
        "Sewing",
        "Painting",
        "Drawing",
        "Pottery",
        "Puzzles",
        "Meditation",
        "Yoga",
        "Video Games",
        "Board Games",
        "Model Building",
        "Writing",
        "Calligraphy",
    ],
    "Outdoor Activities": [
        "Hiking",
        "Camping",
        "Cycling",
        "Jogging",
        "Walking",
        "Fishing",
        "Sailing",
        "Swimming",
        "Horse Riding",
        "Rock Climbing",
        "Surfing",
        "Skiing",
        "Snowboarding",
        "Kayaking",
        "Picnicking",
        "Birdwatching",
    ],
    "Holidays & Celebrations": [
        "Christmas",
        "New Year's Eve",
        "Easter",
        "Halloween",
        "Valentine's Day",
        "Mother's Day",
        "Father's Day",
        "St. Patrick's Day",
        "April Fool's Day",
        "Hanukkah",
        "Carnival",
        "Bastille Day",
        "Bonfire Night",
        "Epiphany",
        "Birthday",
        "Wedding",
    ],
    "Wedding Anniversaries": [
        "Paper",
        "Cotton",
        "Leather",
        "Flowers",
        "Wood",
        "Iron",
        "Bronze",
        "Wool",
        "Tin",
        "Crystal",
        "China",
        "Silver",
        "Pearl",
        "Ruby",
        "Gold",
        "Diamond",
    ],
    "Vacation & Travel": [
        "Hotel",
        "Tent",
        "Camper",
        "Beach",
        "Pool",
        "Spa",
        "Resort",
        "Airport",
        "Airplane",
        "Train",
        "Cruise",
        "Restaurant",
        "Bar",
        "Market",
        "City Tour",
        "Rooftop Terrace",
    ],
    "Party & Group Games": [
        "Charades",
        "Mafia",
        "Werewolf",
        "Musical Chairs",
        "Truth or Dare",
        "Spin the Bottle",
        "Pictionary",
        "Taboo",
        "Heads Up!",
        "Simon Says",
        "Freeze Tag",
        "Hide and Seek",
        "Beer Pong",
        "Dodgeball",
        "Scavenger Hunt",
        "Karaoke",
    ],
    "Clothing": [
        "T-Shirt",
        "Shirt",
        "Blouse",
        "Sweater",
        "Jacket",
        "Coat",
        "Jeans",
        "Pants",
        "Skirt",
        "Dress",
        "Suit",
        "Leggings",
        "Joggers",
        "Scarf",
        "Hat",
        "Shoes",
    ],
    "Furniture": [
        "Bed",
        "Sofa",
        "Armchair",
        "Dining Table",
        "Chair",
        "Desk",
        "Wardrobe",
        "Chest of Drawers",
        "Bookshelf",
        "Coffee Table",
        "TV Stand",
        "Nightstand",
        "Cabinet",
        "Sideboard",
        "Stool",
        "Coat Rack",
    ],
    "Household Appliances": [
        "Refrigerator",
        "Washing Machine",
        "Dishwasher",
        "Microwave",
        "Oven",
        "Stove",
        "Vacuum Cleaner",
        "Iron",
        "Toaster",
        "Coffee Maker",
        "Blender",
        "Mixer",
        "Hair Dryer",
        "Air Conditioner",
        "Heater",
        "Fan",
    ],
    "Electrical Devices": [
        "Television",
        "Laptop",
        "Desktop Computer",
        "Smartphone",
        "Tablet",
        "Printer",
        "Router",
        "Smart Speaker",
        "Game Console",
        "Monitor",
        "Projector",
        "Radio",
        "Lamp",
        "Camera",
        "Smartwatch",
        "VR Headset",
    ],
    "Toys": [
        "Lego",
        "Teddy Bear",
        "Barbie",
        "Hot Wheels",
        "Rubik's Cube",
        "Yo-Yo",
        "Frisbee",
        "Super Soaker",
        "Play-Doh",
        "Rocking Horse",
        "Rag Doll",
        "Game Boy",
        "Building Blocks",
        "Toy Car",
        "Stuffed Animals",
        "Hula Hoop",
    ],
    "Weapons": [
        "Sword",
        "Spear",
        "Bow",
        "Crossbow",
        "Dagger",
        "Axe",
        "Mace",
        "Flail",
        "Rapier",
        "Katana",
        "Halberd",
        "Hammer",
        "Shield",
        "Longsword",
        "Battle Axe",
        "Cannon",
    ],
    "Everyday Items": [
        "Backpack",
        "Wallet",
        "Keys",
        "Umbrella",
        "Watch",
        "Sunglasses",
        "Notebook",
        "Pen",
        "Bottle",
        "Mug",
        "Headphones",
        "Charger",
        "Mirror",
        "Towel",
        "Pillow",
        "Blanket",
    ],
}


@dataclass
class GameState:
    """Tracks the current game state."""

    current_topic: str = ""
    current_items: list[str] = field(default_factory=list)
    d6_value: int = 1
    d8_value: int = 1
    d6_stats: defaultdict[int, int] = field(default_factory=lambda: defaultdict(int))
    d8_stats: defaultdict[int, int] = field(default_factory=lambda: defaultdict(int))


class ChameleonGame:
    """Main game class for The Chameleon CLI."""

    def __init__(self) -> None:
        """Initialize the game with a random topic."""
        self.console: Console = Console()
        self.state: GameState = GameState()
        self._initialize_game()

    def _initialize_game(self) -> None:
        """Initialize the game with a random topic."""
        self.shuffle_topic()

    def _get_random_topic_and_items(self) -> tuple[str, list[str]]:
        """Select a random topic and return 16 random items from it."""
        topics: list[str] = list(GAME_DATA.keys())
        topic: str = random.choice(seq=topics)  # noqa: S311
        all_items: list[str] = GAME_DATA[topic].copy()
        random.shuffle(x=all_items)
        items: list[str] = all_items[:16]  # Take first 16 items
        return topic, items

    def shuffle_topic(self) -> None:
        """Shuffle to a new random topic."""
        topic: str
        items: list[str]
        topic, items = self._get_random_topic_and_items()
        self.state.current_topic, self.state.current_items = topic, items

    def roll_d6(self) -> int:
        """Roll a D6 dice (1-6)."""
        return random.randint(a=1, b=6)  # noqa: S311

    def roll_d8(self) -> int:
        """Roll a D8 dice (1-8)."""
        return random.randint(a=1, b=8)  # noqa: S311

    def roll_both_dice(self) -> tuple[int, int]:
        """Roll both D6 and D8 dice and update statistics."""
        d6: int = self.roll_d6()
        d8: int = self.roll_d8()
        self.state.d6_value = d6
        self.state.d8_value = d8
        self.state.d6_stats[d6] += 1
        self.state.d8_stats[d8] += 1
        return d6, d8

    def display_grid(self) -> None:
        """Display the 4x4 grid with current topic items."""
        if not self.state.current_items:
            self.console.print("[red]No items loaded![/red]")
            return

        table: Table = Table(
            title=f"[bold cyan]Topic: {self.state.current_topic}[/bold cyan]",
            box=box.ROUNDED,
            show_header=True,
            header_style="bold magenta",
        )

        # Add column headers (A, B, C, D)
        table.add_column("", style="bold yellow", width=3)
        for col in range(4):
            table.add_column(chr(65 + col), style=BOLD_BLUE_STYLE, justify="center", width=20)

        # Add rows
        for row in range(4):
            row_label: str = str(row + 1)
            row_data: list[str] = [row_label]
            for col in range(4):
                idx: int = row * 4 + col
                if idx < len(self.state.current_items):
                    item: str = self.state.current_items[idx]
                    row_data.append(item)
                else:
                    row_data.append("")
            table.add_row(*row_data)

        self.console.print(table)

    def display_dice(self, d6: int | None = None, d8: int | None = None) -> None:
        """Display the current dice values."""
        _d6: int = d6 if d6 is not None else self.state.d6_value
        _d8: int = d8 if d8 is not None else self.state.d8_value

        dice_text: Text = Text()
        dice_text.append("🎲 ", style="bold yellow")
        dice_text.append(f"D6: {_d6}", style="bold green")
        dice_text.append("  |  ", style="dim")
        dice_text.append(f"D8: {_d8}", style=BOLD_BLUE_STYLE)

        self.console.print(Panel(dice_text, box=box.ROUNDED, border_style="cyan"))

    def _create_stats_table(
        self,
        title: str,
        dice_stats: defaultdict[int, int],
        max_value: int,
        count_style: str,
    ) -> Table:
        """Create a statistics table for dice rolls."""
        table: Table = Table(title=title, box=box.ROUNDED, show_header=True)
        table.add_column("Value", style="bold cyan", justify="center")
        table.add_column("Count", style=count_style, justify="center")
        table.add_column("Bar", style="yellow")

        max_count: int = max(dice_stats.values()) if dice_stats.values() else 1
        for value in range(1, max_value + 1):
            count: int = dice_stats[value]
            bar_length: int = int((count / max_count) * 20) if max_count > 0 else 0
            bar: str = "█" * bar_length
            table.add_row(str(value), str(count), bar)

        return table

    def display_stats(self) -> None:
        """Display roll statistics."""
        if not any(self.state.d6_stats.values()) and not any(self.state.d8_stats.values()):
            self.console.print("[yellow]No rolls yet. Roll the dice to see statistics![/yellow]")
            return

        d6_table: Table = self._create_stats_table(
            title="[bold]D6 Roll Statistics[/bold]",
            dice_stats=self.state.d6_stats,
            max_value=6,
            count_style="bold green",
        )

        d8_table: Table = self._create_stats_table(
            title="[bold]D8 Roll Statistics[/bold]",
            dice_stats=self.state.d8_stats,
            max_value=8,
            count_style=BOLD_BLUE_STYLE,
        )

        self.console.print(d6_table)
        self.console.print()
        self.console.print(d8_table)

    def run_interactive(self) -> None:
        """Run the game in interactive mode."""
        self.console.print("[bold bright_cyan]🎭 The Chameleon - Interactive Dice Game[/bold bright_cyan]")
        self.console.print("[dim]Type 'help' for commands, 'quit' to exit[/dim]\n")

        while True:
            try:
                self.display_grid()
                self.console.print()
                self.roll_both_dice()
                self.display_dice()
                self.console.print()

                match self.console.input("\n[bold cyan]Command[/bold cyan] (roll/stats/help/quit): ").strip().lower():
                    case "q" | "quit" | "exit":
                        self.console.print("[yellow]Thanks for playing! 👋[/yellow]")
                        break
                    case "r" | "roll" | "":
                        self.shuffle_topic()
                        d6, d8 = self.roll_both_dice()
                        self.console.print("[bold green]Shuffled to new topic![/bold green]")
                        self.console.print("\n[bold green]Rolling dice...[/bold green]")
                        self.display_dice(d6=d6, d8=d8)
                    case "s" | "stats" | "statistics":
                        self.console.print()
                        self.display_stats()
                    case "h" | "help":
                        self._show_help()
                    case _:
                        self.console.print("[red]Unknown command. Type 'help' for available commands.[/red]")

                self.console.print()

            except KeyboardInterrupt:
                self.console.print("\n[yellow]Thanks for playing! 👋[/yellow]")
                break
            except EOFError:
                break

    def _show_help(self) -> None:
        """Display help information."""
        help_text: str = """
[bold cyan]Available Commands:[/bold cyan]

  [bold]roll[/bold] (or [bold]r[/bold])     - Roll both D6 and D8 dice and shuffle to a new random topic
  [bold]stats (or [bold]s[/bold])[/bold]              - Show roll statistics
  [bold]help[/bold] (or [bold]h[/bold])    - Show this help message
  [bold]quit[/bold] (or [bold]q[/bold])    - Exit the game

[bold cyan]How to Play:[/bold cyan]

1. The game displays a 4x4 grid with items from a random topic
2. Roll the dice to get 2 random numbers between 1 and 6 and 1 and 8.
    Non-chamleons use their code card to find the secret item.
3. View statistics to see dice roll frequencies
        """
        self.console.print(Panel(help_text, title="[bold]Help[/bold]", box=box.ROUNDED))


app = typer.Typer(
    name="chameleon",
    help="The Chameleon - Interactive Dice Game CLI",
    add_completion=False,
)


@app.command()
def roll() -> None:
    """Roll the dice once and exit."""
    game = ChameleonGame()
    game.shuffle_topic()
    d6, d8 = game.roll_both_dice()
    game.display_grid()
    game.display_dice(d6=d6, d8=d8)


@app.command()
def interactive() -> None:
    """Run in interactive mode (default)."""
    game = ChameleonGame()
    game.run_interactive()


def main() -> None:
    """Main entry point for the CLI."""
    # Default to interactive mode if no command is provided
    if len(sys.argv) == 1:
        game = ChameleonGame()
        game.run_interactive()

    else:
        app()


if __name__ == "__main__":
    main()
